### ISSUE TITLE
Expose prepare API

### ISSUE THREAD

**Issue by S2Ler** [mergesort/FeedbackEffect#1]
[Preparing the generator can reduce latency when triggering feedback. This is particularly important when trying to match feedback to sound or visual cues.](https://developer.apple.com/documentation/uikit/uifeedbackgenerator)

**Comment by mergesort** [comment]
Hey @diejmon, thanks for the suggestion! I'm out of town for the week, but I'll try and find some time to implement it next week when I get back.

In the mean time I recommend you try it out and see how it feels in your app, cause I haven't noticed any meaningful impact so far, but that of course is one person's experience.

Thanks again!

**Comment by av0c0der** [comment]
Will be fixed by #2

**Comment by S2Ler** [comment]
Let me clarify how `prepare()` should be used by design.

Consider you have an animation and you want to produce feedback effect at the end of the animation at precise point in time. You know that in 0.25 seconds you will need to generate feedback. 

1. At the start of the animation you call: `prepare()`
2. After 0.25 seconds you generate feedback.

Calling `prepare()` before generating feedback allows system to prepare for precise feedback generation. 

@Jauzee There is no need to call `prepare()` right before you call `generateFeedback`. `prepare()` is supposed to be called by the user of the lib. Only the user knows when it is good time to prepare feedback generator (see example above).

**Comment by av0c0der** [comment]
@diejmon thank you for clarifying it, I will revert this change and we'll wait @mergesort to add an API.

**Comment by mergesort** [comment]
Hey @diejmon. I took your suggestion and implemented a `.prepare()` API for `HapticFeedback`. This will allow you to prime your `UIImpactGenerator` before playing back the effects.

You can check it out [here](https://github.com/mergesort/FeedbackEffect/pull/3). Let me know what you think!

**Comment by S2Ler** [comment]
API is good, thanks!

**Comment by mergesort** [comment]
Alrighty. #3 is merged in now and you can use the API by updating to version 1.2.
